CREATE TYPE Color AS ENUM (
    'BROWN',
    'WHITE',
    'BLACK',
    'GREY',
    'BROWN_WHITE',
    'BROWN_BLACK',
    'BROWN_GREY',
    'WHITE_BROWN',
    'WHITE_BLACK',
    'WHITE_GREY',
    'BLACK_BROWN',
    'BLACK_WHITE',
    'BLACK_GREY',
    'GREY_BROWN',
    'GREY_WHITE',
    'GREY_BLACK',
    'MIXED'
    );